---
title: "Extracting EIU Tables"
author: "Xavier Marquez"
date: "`r lubridate::now()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Tables

```{r}
# tables_eiu <- extract_tables("Democracy_Index_2018.pdf")
# tables_eiu <- extract_tables("democracy-index-2020.pdf")

# pdftools::pdf_split("Democracy Index 2019.pdf")

# tables_eiu_2019 <- extract_tables("Democracy Index 2019_0000000000000000000000000000000000000000000000000000000000000000000000020.pdf")
# tables_eiu_2019_2 <- extract_tables("Democracy Index 2019_0000000000000000000000000000000000000000000000000000000000000000000000021.pdf")
# tables_eiu_2019_3 <- extract_tables("Democracy Index 2019_0000000000000000000000000000000000000000000000000000000000000000000000022.pdf")
# tables_eiu_2019_4 <- extract_tables("Democracy Index 2019_0000000000000000000000000000000000000000000000000000000000000000000000023.pdf")
# tables_eiu_2019_5 <- extract_tables("Democracy Index 2019_0000000000000000000000000000000000000000000000000000000000000000000000024.pdf")
# fs::file_delete(new_names[28:50])

tables_eiu <- pdftools::pdf_data("eiu-democracy-index-2021.pdf")

years <- c(2021:2010, 2008, 2006)

suppressWarnings(table_3 <- 34:38 %>% 
  map(~tables_eiu[[.]]) %>% 
  map_df(~{filter(., y > 155, y < 735) %>% 
      group_by(y) %>% 
      summarise(country = paste(text[is.na(as.numeric(text))], collapse = " "), 
                values = list(as.numeric(text[!is.na(as.numeric(text))]))) %>%
      unnest(cols = c(values)) %>%
      group_by(country) %>%
      mutate(year = years[1:n()])}) %>%
  select(-y))

eiu <- table_3 %>%
  filter(!country %in% c("", "average", "World average")) %>%
  rename(eiu = values)

# tables_eiu <- list(tables_eiu_2019[[1]], tables_eiu_2019_2[[1]], tables_eiu_2019_3[[1]], tables_eiu_2019_4[[1]], tables_eiu_2019_5[[1]])

# convert <- function(table) {
#   output <- table %>%
#     as_tibble() %>%
#     filter(!V1 %in% c("", "average", "World average")) 
#   
#   names(output) <- c("country","2019", "2018","2017", 
#                      "2016","2015","2014", "2013",
#                      "2012","2011","2010","2008","2006")
#   
#   output <- output %>% 
#     mutate(country = ifelse(grepl("Ivoire", country), "Cote d'Ivoire", country))
#   
#   output
#   
# }
# 
# eiu <- tables_eiu %>%
#   map_df(convert)

# eiu <- eiu %>%
#   gather(year, eiu, `2019`:`2006`)
# 
# eiu <- eiu %>% mutate(across(c(2:3), as.numeric))

write_csv(eiu, "EIU Democracy Index 2020.csv")
```

