---
title: "Producing a more consistent table of country codes"
output: html_notebook
---

```{r setup, include = FALSE}

library(tidyverse)
library(countrycode)
library(democracyData)
library(lubridate)

read_csv <- memoise::memoise(readr::read_csv)
read_tsv <- memoise::memoise(readr::read_tsv)
read_sav <- memoise::memoise(haven::read_sav)
geocode <- memoise::memoise(ggmap::geocode)

devtools::load_all()

```

This is based on the `countrycode` package's excellent tables.

```{r countrycode_data}

countrycode_data <- countrycode::countrycode_data %>%
  as_tibble() %>%
  rename(official.continent = continent,
         official.region = region,
         official.cown = cown,
         official.cowc = cowc) %>%
  mutate(official.cown = ifelse(is.na(official.cown) & country.name.en == "Serbia", 345, official.cown),
         official.cowc = ifelse(is.na(official.cowc) & country.name.en == "Serbia", "YUG", official.cowc))
```

```{r official_cow_data}

official_cow <- read_csv("http://www.correlatesofwar.org/data-sets/state-system-membership/states2016") %>%
  rename(official.cowc = stateabb, 
         official.cown = ccode,
         cow_country_name = statenme) %>%
  mutate(cow_startdate = ymd(paste(styear, stmonth, stday, sep = "-")),
         cow_enddate = ymd(paste(endyear, endmonth, endday, sep = "-")),
         cow_enddate = as_date(ifelse(endyear == 2016 & endmonth == 12 & endday == 31, NA, (cow_enddate)))) %>%
  select(-starts_with("st"), -starts_with("end"), -version)
```

```{r official_gwn_data}
official_gwn <- read_tsv("http://privatewww.essex.ac.uk/~ksg/data/iisystem.dat",
                         col_names = c("GWn", "GWc", "official_GW_country", "official_GW_startdate", "official_GW_enddate"),
                         col_types = cols(GWn = col_integer(),
                                          GWc = col_character(),
                                          official_GW_country = col_character(),
                                          official_GW_startdate = col_date(format = "%d:%m:%Y"),
                                          official_GW_enddate = col_date(format = "%d:%m:%Y"))) %>%
  mutate(official_GW_enddate = as_date(ifelse(official_GW_enddate == ymd("2012-12-31"), NA, (official_GW_enddate))),
         microstate = FALSE)

official_micro <- read_tsv("http://privatewww.essex.ac.uk/~ksg/data/microstatessystem.dat",
                         col_names = c("GWn", "GWc", "official_GW_country", "official_GW_startdate", "official_GW_enddate"),
                         col_types = cols(GWn = col_integer(),
                                          GWc = col_character(),
                                          official_GW_country = col_character(),
                                          official_GW_startdate = col_date(format = "%d:%m:%Y"),
                                          official_GW_enddate = col_date(format = "%d:%m:%Y"))) %>%
  mutate(official_GW_enddate = as_date(ifelse(official_GW_enddate == ymd("2012-12-31"), NA, (official_GW_enddate))),
         microstate = TRUE)

official_gwn <- bind_rows(official_gwn, official_micro)

rm(official_micro)
```

```{r official_polity}
official_polity <- read_sav("http://www.systemicpeace.org/inscr/p4v2016d.sav") %>%
  rename(official_polity_ccode = ccode, 
         official_polity_scode = scode,
         official_polity_country = country) %>%
  mutate(eyear = ifelse(eyear == 9999, NA, eyear),
         emonth = ifelse(emonth == 99, NA, emonth),
         eday = ifelse(eday == 99, NA, eday),
         polity_startdate = ymd(paste(byear, bmonth, bday, sep = "-")),
         polity_enddate = ymd(paste(eyear, emonth, eday, sep = "-")))  %>%
  select(starts_with("official"), ends_with("date")) %>%
  group_by(official_polity_country, official_polity_ccode, official_polity_scode) %>%
  mutate(diff_date = lead(polity_startdate) - polity_enddate,
         period = (count_sequence_breaks(diff_date, seq_step = 0))) %>%
  fill(period) %>%
  group_by(period = (count_sequence_breaks(diff_date, seq_step = 0)), add = TRUE) %>%
  summarise(polity_startdate = min(polity_startdate, na.rm = TRUE), polity_enddate = max(polity_enddate)) %>%
  group_by(official_polity_ccode, official_polity_scode, official_polity_country) %>%
  mutate(big_gap = lead(polity_startdate) - polity_enddate) %>%
  fill(big_gap) %>%
  mutate(period = lead(big_gap), 
         period = ifelse(is.na(period) & big_gap == 1, 1, period), 
         period = ifelse(period == 1 & big_gap > 1, big_gap, period)) %>%
  group_by(official_polity_ccode, official_polity_scode, official_polity_country, period) %>%
  summarise(polity_startdate = min(polity_startdate), polity_enddate = max(polity_enddate)) %>%
  select(-period) %>%
  ungroup()
  
  

official_polity %>% filter(official_polity_ccode %in% c(255, 260, 265))
official_polity %>% filter(official_polity_ccode %in% c(365, 364))
official_polity %>% filter(official_polity_ccode %in% c(345, 347))
official_polity %>% filter(official_polity_ccode %in% c(815:818))

official_polity %>% 
  group_by(official_polity_ccode) %>% 
  filter(any(!is.na(polity_enddate)))
```

```{r old_table_data}

old_table_data <- read_csv("./data.csv") %>% 
  mutate(country_name = ifelse(grepl("Cote D",country_name),"Cote D'Ivoire",country_name),
         country_name = plyr::mapvalues(country_name, 
                                        from = c("Württemberg","São Tomé and Principe"),
                                        to = c("Wurttemberg","Sao Tome and Principe")),
         country_name = stringr::str_conv(country_name,"ASCII")) %>%
  select(-num_periods, -problem_history, -cow_startdate, -cow_enddate, -microstate) %>%
  rename(extended_country_name = country_name,
         extended_region = region,
         extended_continent = continent) %>%
  mutate(official.cown = cown,
         unofficial.GWn = GWn,
         unofficial.GWc = GWc) %>%
  select(-polity_startdate, -polity_enddate, -polity_country, -cowc)

old_table_data %>% filter(grepl("Vie", extended_country_name))
official_cow %>% filter(grepl("Vie", cow_country_name))
official_polity %>% filter(grepl("Vie", official_polity_country))


old_table_data <- old_table_data %>%
  mutate_at(vars(cown, polity_ccode, official.cown), ~ifelse(old_table_data$GWn == 815, NA, .))

my_additions <- anti_join(old_table_data, official_gwn) %>%
  rename(unofficial_startdate = GW_startdate,
         unofficial_enddate = GW_enddate,
         extended_GWn = GWn,
         extended_GWc = GWc) %>%
  select(contains("extended"), regex, contains("unofficial_"), lat, lon) 

old_table_data <- old_table_data %>%
  filter(!extended_country_name %in% my_additions$extended_country_name)


connector_table <- old_table_data %>% 
  filter(!extended_country_name %in% my_additions$extended_country_name) %>%
  select(-GW_startdate, -GW_enddate, -GW_membership, -unofficial.GWn, -unofficial.GWc) %>%
  distinct()  %>%
  mutate(polity_ccode = ifelse(polity_ccode %in% c(711, 563), NA, polity_ccode)) %>%
  left_join(official_polity, by = c(polity_ccode = "official_polity_ccode")) %>%
  rename(polity_scode = official_polity_scode)

anti_join(official_polity, connector_table)
anti_join(connector_table, official_polity)
connector_table %>% filter(grepl("Germ", extended_country_name))
connector_table %>% filter(grepl("Vie", extended_country_name))

```

```{r connecting_datasets}

no_cown <- connector_table %>%
  filter(is.na(cown)) 

not_in_cow <- anti_join(connector_table  %>%
                              filter(!is.na(official.cown)) %>%
                              distinct(), official_cow) %>%
  mutate(cown = NA, official.cown = NA) %>%
  bind_rows(no_cown) %>%
  select(-official.cown)

join_to_cow <- connector_table %>%
  distinct() %>%
  filter(!is.na(official.cown), 
         !extended_country_name %in% not_in_cow$extended_country_name)
                                     
new_table_data <- full_join(official_cow, join_to_cow) %>%
  full_join(countrycode_data %>%
              select(-p4_ccode, -p4_scode)) %>%
  distinct()

new_table_data %>% filter(is.na(cown)) %>% pull(country.name.en) %>% unique()

new_table <- new_table_data %>%
  bind_rows(not_in_cow) %>%
  full_join(official_gwn) %>%
  bind_rows(my_additions) %>%
  distinct() %>%
  select(dplyr::matches("_country|country.name.en$"), contains("GWn"), contains("cown"), dplyr::matches("polity_ccode|polity_scode|p4"), contains("date"), everything())

new_table %>% filter(official.cown != cown)
new_table %>% filter(!is.na(official.cown), is.na(cown))
new_table %>% filter(is.na(official.cown), !is.na(cown))
new_table <- new_table %>% 
  select(-official.cown)

new_table <- new_table %>%
  mutate(extended_GWn = ifelse(is.na(extended_GWn), GWn, extended_GWn),
         extended_GWc = ifelse(is.na(extended_GWc), GWc, extended_GWc))

new_table %>% filter(grepl("Germ", extended_country_name))

new_table <- new_table %>% 
  group_by_at(vars(-contains("date"))) %>%
  mutate(polity_cow_overlap = int_overlaps(polity_startdate %--% if_else(is.na(polity_enddate), as_date(now()), polity_enddate), 
                                           cow_startdate %--% if_else(is.na(cow_enddate), as_date(now()), cow_enddate)),
         polity_GW_overlap = int_overlaps(polity_startdate %--% if_else(is.na(polity_enddate), as_date(now()), polity_enddate), 
                                          official_GW_startdate %--% if_else(is.na(official_GW_enddate), as_date(now()), official_GW_enddate)),
         cow_GW_overlap = int_overlaps(cow_startdate %--% if_else(is.na(cow_enddate), as_date(now()), cow_enddate), 
                                       official_GW_startdate %--% if_else(is.na(official_GW_enddate), as_date(now()), official_GW_enddate)),
         max_overlap = polity_cow_overlap + polity_GW_overlap + cow_GW_overlap) %>%
  filter(max_overlap == max(max_overlap) | is.na(max_overlap)) %>%
  ungroup() %>%
  select(-ends_with("overlap"))

new_table %>% filter(grepl("Germ", extended_country_name))


```

```{r fixing_country_names}

new_table %>% filter(is.na(country.name.en))
new_table %>% filter(is.na(extended_country_name))

new_table <- new_table %>%
  mutate(extended_country_name = ifelse(is.na(extended_country_name), country.name.en, extended_country_name))
  
new_table 

rm(join_to_cow, connector_table, countrycode_data, my_additions, new_table_data, no_cown, not_in_cow, old_table_data)
```

```{r}

new_table %>%
  filter(extended_country_name == 'Serbia')

new_table %>%
  filter(extended_country_name == 'Yugoslavia')

```

```{r}
new_table <- new_table %>%
  mutate(GW_membership = !is.na(microstate),
         polity_membership = !is.na(polity_startdate),
         cow_membership = !is.na(cow_startdate))

new_table %>% filter(!polity_membership)
new_table %>% filter(!cow_membership)
new_table %>% filter(!GW_membership)
```

```{r}
new_table %>% filter(extended_region != official.region)
new_table %>% filter(!is.na(extended_region) & is.na(official.region))
new_table %>% filter(is.na(extended_region) & !is.na(official.region))

new_table <- new_table %>%
  mutate(extended_region = if_else(is.na(extended_region), official.region, extended_region),
         extended_continent = if_else(is.na(extended_continent), official.continent, extended_continent))

new_table %>% filter(extended_region != official.region)
new_table %>% filter(!is.na(extended_region) & is.na(official.region))
new_table %>% filter(is.na(extended_region) & !is.na(official.region))
new_table %>% filter(is.na(extended_region))
new_table %>% filter(is.na(extended_continent))

```

```{r}

new_table %>% filter(regex != country.name.en.regex) %>%
  select(regex, country.name.en.regex)

new_table %>% filter(is.na(regex), !is.na(country.name.en.regex)) %>%
  select(regex, country.name.en.regex)

new_table <- new_table %>%
  mutate(regex = ifelse(is.na(regex)  & !is.na(country.name.en.regex), 
                         country.name.en.regex, regex))

new_table %>% group_by(extended_country_name) %>% filter(any(is.na(lon)))

new_table %>% filter(extended_country_name == "Western Sahara")

## Get rid of an extra Western Sahara

new_table$country.name.en[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$country.name.en[ new_table$regex == "western.sahara" ]
new_table$ar5[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$ar5[ new_table$regex == "western.sahara" ]
new_table$official.continent[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$official.continent[ new_table$regex == "western.sahara" ]
new_table$eurocontrol_pru[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$eurocontrol_pru[ new_table$regex == "western.sahara" ]
new_table$eurocontrol_statfor[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$eurocontrol_statfor[ new_table$regex == "western.sahara" ]
new_table$fips105[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$fips105[ new_table$regex == "western.sahara" ]
new_table$icao[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$icao[ new_table$regex == "western.sahara" ]
new_table$icao_region[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$icao_region[ new_table$regex == "western.sahara" ]
new_table$iso2c[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$iso2c[ new_table$regex == "western.sahara" ]
new_table$iso3c[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$iso3c[ new_table$regex == "western.sahara" ]
new_table$iso3n[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$iso3n[ new_table$regex == "western.sahara" ]
new_table$official.region[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$official.region[ new_table$regex == "western.sahara" ]
new_table$un[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$un[ new_table$regex == "western.sahara" ]
new_table$wb[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$wb[ new_table$regex == "western.sahara" ]
new_table$country.name.de[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$country.name.de[ new_table$regex == "western.sahara" ]
new_table$country.name.de.regex[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$country.name.de.regex[ new_table$regex == "western.sahara" ]
new_table$eurostat[ new_table$regex == "western.sahara|sahrawi" ] <- new_table$eurostat[ new_table$regex == "western.sahara" ]


new_table <- new_table %>%
  filter(!(regex == "western.sahara"))

## Get rid of an extra Palestine

new_table %>% filter(grepl("Pales", extended_country_name))

new_table %>% filter(grepl("Palestine, State of", extended_country_name)) %>% glimpse()

new_table$country.name.en[ new_table$regex == "^(?!.*british.*)palestin(?!.*british)|west bank|gaza" ] <- "Palestine, State of"

new_table$ar5[ new_table$country.name.en == "Palestine, State of" ] <- "MAF"
new_table$official.continent[ new_table$country.name.en == "Palestine, State of" ] <- "Asia"
new_table$eurocontrol_pru[ new_table$country.name.en == "Palestine, State of" ] <- "Middle East"
new_table$eurocontrol_statfor[ new_table$country.name.en == "Palestine, State of" ] <- "Middle-East"
new_table$icao[ new_table$country.name.en == "Palestine, State of" ] <- "LV"
new_table$icao_region[ new_table$country.name.en == "Palestine, State of" ] <- "L"
new_table$imf[ new_table$country.name.en == "Palestine, State of" ] <- 487
new_table$ioc[ new_table$country.name.en == "Palestine, State of" ] <- "PLE"
new_table$iso2c[ new_table$country.name.en == "Palestine, State of" ] <- "PS"
new_table$iso3c[ new_table$country.name.en == "Palestine, State of" ] <- "PSE"
new_table$iso3n[ new_table$country.name.en == "Palestine, State of" ] <- 275
new_table$official.region[ new_table$country.name.en == "Palestine, State of" ] <- "Western Asia"
new_table$un[ new_table$country.name.en == "Palestine, State of" ] <- 275
new_table$wb[ new_table$country.name.en == "Palestine, State of" ] <- "WBG"
new_table$country.name.de[ new_table$country.name.en == "Palestine, State of" ] <- "Palästina"
new_table$country.name.de.regex[ new_table$country.name.en == "Palestine, State of" ] <- "pal(ä|a)stin|\\bgaza|west.?bank"
new_table$country.name.en.regex[ new_table$country.name.en == "Palestine, State of" ] <- "palestin|\\bgaza|west.?bank"
new_table$eurostat[ new_table$country.name.en == "Palestine, State of" ] <- "PS"
new_table$wb_api2c[ new_table$country.name.en == "Palestine, State of" ] <- "PS"
new_table$wb_api3c[ new_table$country.name.en == "Palestine, State of" ] <- "PSE"
new_table$wvs[ new_table$country.name.en == "Palestine, State of" ] <- 275
new_table$regex[ new_table$country.name.en == "Palestine, State of" ] <- "^(?!.*british.*)palestin(?!.*british)|west bank|gaza"

new_table %>% filter(grepl("Palestine, State of", extended_country_name)) %>% glimpse()

new_table <- new_table %>% 
  filter(!(extended_country_name == "Palestine, State of" & is.na(unofficial_startdate)))

to_geocode <- new_table %>% 
  filter(is.na(lon)) %>% 
  pull(country.name.en)

to_geocode

results <- geocode(to_geocode)

results <- results %>%
  as_tibble() %>%
  mutate(country.name.en = to_geocode)

new_table$lat[ new_table$country.name.en %in% results$country.name.en ] <- results$lat
new_table$lon[ new_table$country.name.en %in% results$country.name.en ] <- results$lon

new_table %>% filter(is.na(lon) | is.na(lat))

data <- new_table

data <- data %>%
  rename(polity_country_name = official_polity_country,
         cowc = official.cowc,
         GW_startdate = official_GW_startdate,
         GW_enddate = official_GW_enddate,
         GW_country_name = official_GW_country)

names(data) <- stringr::str_replace_all(names(data), "\\.", "_")  

data <- data %>% select(ends_with("country_name"), 
                        ends_with("GWn"), 
                        ends_with("GWc"), 
                        dplyr::matches("cow(n|c)$"), 
                        dplyr::matches("polity_(c|s)code$"), 
                        ends_with("date"), 
                        ends_with("membership"), 
                        regex, 
                        lat, lon, everything())

devtools::use_data(data, internal = TRUE, overwrite = TRUE)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
