#' Extended UDS
#'
#' A dataset extending the Unified Democracy Scores of Pemstein, Meserve, and
#' Melton (2010) to the 19th century (and sometimes before), updating it with
#' 2013-2022 data, and calculating scores for countries not in the official UD
#' release. Cite both Pemstein, Meserve, and Melton 2010 as well as Marquez
#' 2016.
#'
#' @section Overview:
#'
#'   This dataset contains an extension of the Unified Democracy Scores of
#'   Pemstein, Meserve, and Melton (2010). PMM 2010 use a latent variable
#'   approach to combine diverse measurements of democracy for a broad panel of
#'   countries from 1946 to 2012; this dataset extends the scores by using more
#'   democracy measures with broader temporal and spatial coverage, generating
#'   democracy scores for `r nrow(extended_uds)` country-years
#'   (`r length(unique(extended_uds$extended_country_name))` distinct countries and
#'   non-sovereign territories). It is generated by the function
#'   [generate_extended_uds].
#'
#'   The measurement of democracy is complicated and controversial. The extended
#'   UDS makes few judgments about what measures of democracy should be used to
#'   generate latent democracy scores, as long as they have been used in
#'   scholarly work. It uses dichotomous, trichotomous, ordinal, and continuous
#'   indices; indices that focus primarily on the "competition" and indices that
#'   focus on the "participation" dimension of democracy; "thick" indices that
#'   attempt to measure a wide variety of characteristics plausibly attributed
#'   to democracy; and "minimalist" indexes that restrict themselves to the bare
#'   minimum of competition. Nevertheless, most of these indexes agree that
#'   democracy has something to do with competition and participation, even if
#'   they weight these dimensions somewhat differently, and even if they include
#'   other things, such as civil rights.
#'
#'   The latent variable score is calculated using the democracy measures from
#'   the following datasets: [anckar], [anrr], [arat_pmm], [blm], [bmr]
#'   (`democracy_femalesuffrage` indicator only), [bnr_extended], [bti],
#'   [bollen_pmm], [svmdi] (continuous indicator), [doorenspleet], [eiu], [fh](donwload_fh.html)
#'   (`fh_total_reversed` indicator), [fh_electoral], [gwf_all_extended],
#'   [hadenius_pmm], [kailitz] (trichotomous indicator of democracy, with
#'   electoral autocracy as the middle category), [LIED], [magaloni_extended],
#'   [mainwaring], [munck_pmm], [pacl], [pacl_update], [peps] (PEPS1v
#'   indicator), [pitf] (non-binary indicator), [polity] (polity 2 indicator),
#'   [polyarchy] (both contestation and participation dimensions),
#'   [polyarchy_dimensions] (both contestation and participation dimensions),
#'   [prc], [REIGN], [svolik], [ulfelder_extended], [utip] (trichotomous
#'   indicator, with one-party democracy as the middle category), the
#'   `v2x_polyarchy` indicator from [vdem_simple], [vanhanen] (the
#'   vanhanen_democratization indicator only), [wgi], and
#'   [wahman_teorell_hadenius] (the from the `regimenyrobust` variable). Please
#'   refer to the documentation of [generate_democracy_scores_dataset] for more
#'   details on these measures of democracy, and to Marquez 2016 for more
#'   details on the construction of the extended latent variable model used to
#'   generate the scores.
#'
#' @section Variables:
#'
#'   \describe{
#'
#'   \item{z1, z1_adj, z1_as_prob, z1_adj_as_prob}{The latent democracy score.
#'   `z1` is the "raw" (unadjusted) score, with mean approximately 0 and sd 1;
#'   `z1_adj` is the version adjusted so that 0 represents the average cutpoint
#'   for the dichotomous indicators composing the index; the `_as_prob` versions
#'   adjust these to the 0-1 range by applying [stats::pnorm] (treating them as
#'   probability measures).}
#'
#'   \item{se_z1}{The standard error of the score.}
#'
#'   \item{_pct025, _pct975}{The latent democracy score 95% confidence
#'   intervals.}
#'
#'   \item{num_measures}{The number of measures that contributed to the index
#'   for the particular country-year. Varies from
#'   `r min(extended_uds$num_measures)` to `r max(extended_uds$num_measures)`; one
#'   can filter the dataset to include only scores where more than, say, 5
#'   measures have contributed to the index.}
#'
#'   \item{measures}{The names of the specific measures that contributed to the
#'   index in that particular country-year. This is a list-column; use
#'   [tidyr::unnest] to unnest. See the documentation for
#'   [generate_democracy_scores_dataset] for specific info about any particular
#'   measure.}
#'
#'   }
#'
#' @template standard-variables
#'
#' @references
#'
#' Marquez, Xavier. 2016. A Quick Method for Extending the Unified Democracy
#' Scores (March 23, 2016). Available at SSRN:
#' \url{http://ssrn.com/abstract=2753830}
#'
#' Pemstein, Daniel, Stephen Meserve, and James Melton. 2010. Democratic
#' Compromise: A Latent Variable Analysis of Ten Measures of Regime Type.
#' Political Analysis 18 (4): 426-449. DOI:10.1093/pan/mpq020
#'
#' @family democracy
#' @family latent variable indexes of democracy
#' @author Xavier Marquez, Political Science and International Relations
#'   Programme, Victoria University of Wellington, marquez.x@gmail.com
"extended_uds"

